#!/bin/bash
MSG_FILE=$1
FILE_CONTENT="$(cat $MSG_FILE)"

REGEX="(^[0-9]{4,}|^[0-9]{4,}\(\w{3,}\)):\s\w+"

if [[ !($FILE_CONTENT =~ $REGEX) ]]; then
  echo ""
  echo "[POLICY] Your message is not formatted correctly"
  echo "Your message should be started with number branch min 4 digits"
  echo "Your message should be in the formats:"
  echo "  1 - branch: commit message"
  echo "  2 - branch(chore/fix/refactor/test/doc): commit message"
  echo ""
  exit 1
fi